Alter TABLE Event DROP FOREIGN KEY;
Alter TABLE Cases DROP FOREIGN KEY;

DROP TABLE Event;
DROP TABLE Cases;
DROP TABLE Person;


CREATE TABLE Person (
	PersonID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FName VARCHAR (30) NOT NULL,
	MInitial VARCHAR (1) NULL,
	LName VARCHAR (30) NOT NULL,
	Address VARCHAR (200) NOT NULL,
	LastContactDay DATETIME NOT NULL,
	Status BIT NOT NULL);

CREATE TABLE Cases (
	CaseID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CaseNum varchar(100) NOT NULL,
	WeeklyReq BIGINT NOT NULL,
	HoursAssigned BIGINT NOT NULL,
	AgencyContactDate DATETIME NOT NULL,
	EstimatedCompletionDate DATETIME NOT NULL,
	Status BIT NOT NULL,
  	PersonID BIGINT NOT NULL,
	INDEX (PersonID),
	FOREIGN KEY (PersonID) REFERENCES Person (PersonID));

CREATE TABLE Event (
	EventID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TimeIn DATETIME NOT NULL,
	TimeOut DATETIME NOT NULL,
	CaseID BIGINT NOT NULL,
  	INDEX (CaseID),
	FOREIGN KEY (CaseID) REFERENCES Cases (CaseID));
	